name: Helm Artifactory

on: push

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install helm"
        uses: mamezou-tech/setup-helmfile@v1.0.0

      - name: "Auth to artifactory"  
        run: |
          helm repo add helm-helm https://cyseereng.jfrog.io/artifactory/api/helm/helm-helm --username ${{ secrets.ARTIFACTORY_HELM_USERNAME }} --password ${{ secrets.ARTIFACTORY_HELM_PASSWORD }}
          curl -u${{ secrets.ARTIFACTORY_HELM_USERNAME }}:${{ secrets.ARTIFACTORY_HELM_PASSWORD }} -T ./hellochart "https://cyseereng.jfrog.io/artifactory/helm-helm/hellochart"
        
        