name: Helm lint, test, package and publish

on: push

jobs:
  helm-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Helm package"
        uses: draios/action-helm-tools@v1.0.1
        with:
          action: "package"
        env:
          CHART_DIR: ./hellochart
          ARTIFACTORY_URL: https://cyseereng.jfrog.io/ui/admin/repositories/local/helm-repos
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_HELM_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_HELM_PASSWORD }}

      - name: "Helm publish"
        uses: draios/action-helm-tools@v1.0.1
        with:
          action: "publish"
        env:
          CHART_DIR: ./hellochart
          ARTIFACTORY_URL: https://cyseereng.jfrog.io/ui/admin/repositories/local/helm-repos
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_HELM_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_HELM_PASSWORD }}
